name: reporting
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Maurice McCabe <mmcc007@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

# TODO(tek08): I don't have control of pub.dev for these packages, so for now,
#   folks can depend on them path-wise, as I have done here.  Each of mmcc007's
#   projects should be cloned into the same parent directory as this project.

dependencies:
  http: ^0.13.5
  usage: 3.4.1
#  tool_base: ^1.9.5+2
  tool_base:
    path: ../tool_base
dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.22.2
  mockito: ^5.3.2
  tool_base_test:
#    git: https://github.com/mmcc007/tool_base_test.git
    path: ../tool_base_test
  args: ^2.3.2
  quiver: ^2.0.5
  meta: ^1.1.8